"""about_me last_seen fields added to user

Revision ID: 48321d032f7d
Revises: 49fd70710a2a
Create Date: 2020-09-04 16:55:09.419679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48321d032f7d'
down_revision = '49fd70710a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
